-- ************************** SqlDBM: Microsoft SQL Server **************************
-- * Generated by SqlDBM: db_ES_resin_recycling_process, v16 by nastusha-90@mail.ru *


-- ************************************** [dbo].[rectification_columns]
CREATE TABLE [dbo].[rectification_columns]
(
 [id]     int NOT NULL ,
 [number] int NOT NULL ,


 CONSTRAINT [PK_rectification_columns] PRIMARY KEY CLUSTERED ([id] ASC)
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Список ректификационных колонн', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rectification_columns';
GO

CREATE TABLE [dbo].[rectification_column_parameters]
(
 [id]                      int NOT NULL ,
 [rectification_column_id] int NOT NULL ,
 [name]                    varchar(200) NOT NULL ,
 [description]             ntext NOT NULL ,


 CONSTRAINT [PK_rectification_column_parameters] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_rectification_column_parameters_rectification_column_id_rectification_columns] FOREIGN KEY ([rectification_column_id])  REFERENCES [dbo].[rectification_columns]([id])
);
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Справочник параметров ректификационной колонны', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rectification_column_parameters';
GO

CREATE TABLE [dbo].[recommended_parameters]
(
 [id]                 NOT NULL ,
 [current_mark_id]   int NOT NULL ,
 [grid_parameter_id] bigint NOT NULL ,
 [created_at]        datetime2(3) NOT NULL ,


 CONSTRAINT [PK_recommended_parameters] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_recommended_parameters_current_mark_id_current_selected_mark] FOREIGN KEY ([current_mark_id])  REFERENCES [dbo].[current_selected_mark]([id]),
 CONSTRAINT [FK_recommended_parameters_grid_parameter_id_grid_search_parameters] FOREIGN KEY ([grid_parameter_id])  REFERENCES [dbo].[grid_search_parameters]([id])
);
GO

CREATE TABLE [dbo].[naphthalene_fraction_temperatures]
(
 [id]                      bigint NOT NULL ,
 [measured_at]             datetime2(3) NOT NULL ,
 [value]                   float NOT NULL ,
 [rectification_column_id] int NOT NULL ,


 CONSTRAINT [PK_naphthalene_fraction_temperatures] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_naphthalene_fraction_temperatures_rectification_column_id_rectification_columns] FOREIGN KEY ([rectification_column_id])  REFERENCES [dbo].[rectification_columns]([id])
);
GO

CREATE TABLE [dbo].[naphthalene_fraction_consumptions]
(
 [id]                      bigint NOT NULL ,
 [measured_at]             datetime2(3) NOT NULL ,
 [value]                   float NOT NULL ,
 [rectification_column_id] int NOT NULL ,


 CONSTRAINT [PK_naphthalene_fraction_consumptions] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_naphthalene_fraction_consumptions_rectification_column_id_rectification_columns] FOREIGN KEY ([rectification_column_id])  REFERENCES [dbo].[rectification_columns]([id])
);
GO

CREATE TABLE [dbo].[marks_catalog]
(
 [id]          int NOT NULL ,
 [name]        nvarchar(150) NOT NULL ,
 [lower_bound] int NOT NULL ,
 [upper_bound] int NOT NULL ,


 CONSTRAINT [PK_marks_catalog] PRIMARY KEY CLUSTERED ([id] ASC)
);
GO

CREATE TABLE [dbo].[grid_search_parameters]
(
 [id]           bigint NOT NULL ,
 [parameter_id] int NOT NULL ,
 [value]        float NOT NULL ,


 CONSTRAINT [PK_grid_search_parameters] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_grid_search_parameters_parameter_id_rectification_column_parameters] FOREIGN KEY ([parameter_id])  REFERENCES [dbo].[rectification_column_parameters]([id])
);
GO


CREATE NONCLUSTERED INDEX [FK_grid_search_parameters_parameter_id_rectification_column_parameters] ON [dbo].[grid_search_parameters] 
 (
  [parameter_id] ASC
 )

GO

CREATE TABLE [dbo].[current_selected_mark]
(
 [id]        int NOT NULL ,
 [timestamp] datetime2(7) NOT NULL ,
 [mark_id]   int NOT NULL ,


 CONSTRAINT [PK_current_selected_marks] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_current_selected_marks_mark_id_marks_catalog] FOREIGN KEY ([mark_id])  REFERENCES [dbo].[marks_catalog]([id])
);
GO

CREATE TABLE [dbo].[chemical_parameters]
(
 [id]                       NOT NULL ,
 [name]                    varchar(200) NOT NULL ,
 [description]             ntext NOT NULL ,
 [rectification_column_id] int NOT NULL ,


 CONSTRAINT [PK_chemical_parameters] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_chemical_parameters_rectification_column_id_rectification_columns] FOREIGN KEY ([rectification_column_id])  REFERENCES [dbo].[rectification_columns]([id])
);
GO

CREATE TABLE [dbo].[chemical_analysis]
(
 [id]                    int NOT NULL ,
 [measured_at]           datetime2(3) NOT NULL ,
 [grid_parameter_id]     bigint NOT NULL ,
 [mark_id]               int NOT NULL ,
 [chemical_parameter_id]  NOT NULL ,
 [value]                 float NOT NULL ,


 CONSTRAINT [PK_chemical_analysis] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_chemical_analysis_chemical_parameter_id_chemical_parameters] FOREIGN KEY ([chemical_parameter_id])  REFERENCES [dbo].[chemical_parameters]([id]),
 CONSTRAINT [FK_chemical_analysis_grid_parameter_id_grid_search_parameters] FOREIGN KEY ([grid_parameter_id])  REFERENCES [dbo].[grid_search_parameters]([id]),
 CONSTRAINT [FK_chemical_analysis_mark_id_marks_catalog] FOREIGN KEY ([mark_id])  REFERENCES [dbo].[marks_catalog]([id])
);
GO

CREATE TABLE [dbo].[absorption_fraction_temperatures]
(
 [id]                      bigint NOT NULL ,
 [rectification_column_id] int NOT NULL ,
 [measured_at]             datetime2(3) NOT NULL ,
 [value]                   float NOT NULL ,


 CONSTRAINT [PK_absorption_fraction_temperatures] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_absorption_fraction_temperatures_rectification_column_id_rectification_columns] FOREIGN KEY ([rectification_column_id])  REFERENCES [dbo].[rectification_columns]([id])
);
GO

CREATE TABLE [dbo].[absorption_fraction_consumptions]
(
 [id]                      bigint NOT NULL ,
 [rectification_column_id] int NOT NULL ,
 [measured_at]             datetime2(3) NOT NULL ,
 [value]                   float NOT NULL ,


 CONSTRAINT [PK_absorption_fraction_consumptions] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_absorption_fraction_consumptions_rectification_column_id_rectification_columns] FOREIGN KEY ([rectification_column_id])  REFERENCES [dbo].[rectification_columns]([id])
);
GO